### ISSUE TITLE
NimbleX discontinued

### ISSUE THREAD

**Issue by OkayPJ** [FabioLolix/LinuxTimeline#210]
* Name: NimbleX
* Discontinuation statement URL if available
https://distrowatch.com/table.php?distribution=nimblex

**Comment by FabioLolix** [comment]
You are pleased to search for first hand information instead of relying to third-party, it marked discontinued on distrowatch is not a valid discontinuation statement URL.

The project is still alive 
* https://nimblex.net/
* https://github.com/NimbleX/nimblex


However it haven't released any images in likely a decade, haven't decided yet if keep or remove it for now

**Comment by FabioLolix** [comment]
Will stay for now
