### ISSUE TITLE
Please, put "gnuclad" in a Github repo or, at least, give instructions to build in rpm-based systems

### ISSUE THREAD

**Issue by q2dg** [FabioLolix/LinuxTimeline#223]
I want to self-host this repo to be able to generate my own linux timelines but I'm using Fedora and gnuclad seems to be only easily available in Ubuntu (via Launchpad) and Arch (via AUR) systems. 
Thanks a lot

**Comment by FabioLolix** [comment]
Hello

> put "gnuclad" in a Github repo

There is already the source repo imported on github https://github.com/FabioLolix/gnuclad

> give instructions to build in rpm-based systems

On the devel branch there is an RPM .spec file taken from a launchpad issue, I have not tested it and in the meantime I have made a patch release for fixing a build bug so the source need to be adjusted

For packaging you need to ask to your distributions community

otherwise for compiling is a classic
```
./configure
make
make install
```

**Comment by q2dg** [comment]
Oooh, thanks a lot!! It's just what I was looking for!
I'll close this issue after your clear explanation, if you don't mind.
