### ISSUE TITLE
More Releases?

### ISSUE THREAD

**Issue by danhunsaker** [FabioLolix/LinuxTimeline#28]
Latest release is 16.12... Curious what the plans are for more recent releases? Looked like monthly releases were the plan, at least at first; could probably tag commits from previous months and generate releases for each? I'd offer to do so myself, but no repo access. :grinning:

**Comment by FabioLolix** [comment]
Hello Dan, I'm sorry for taking so long to reply.

Next release will be out in September!
Hopefully future release will not be so distant, let's say not more than 3 months each.
If you have some request or tips it's time now :)

Last year I and Konimex were more active and there was monthly or bimonthly releases.

> could probably tag commits from previous months and generate releases for each?

No because each tag is accompanied with respective changelog and new version in gldt.conf


I have several additions and update to make, keeping up with ditrowatch and a new distributions.md file will come.

**Comment by danhunsaker** [comment]
Ah. Fair enough on the retroactive releases. Wonder if the release process could be automated to some extent?

September it is!

**Comment by noxarivis** [comment]
@danhunsaker
What do you mean by "September it is"?

**Comment by danhunsaker** [comment]
Hmm. Fair point. That's a potentially confusing phrase. Mostly just acknowledging that the next release is expected in September.

**Comment by FabioLolix** [comment]
> next release is expected in September.

Delayed to 29 October, marking 5 years since last version from the original autors

**Comment by FabioLolix** [comment]
Done https://github.com/FabioLolix/LinuxTimeline/releases/tag/v17.10

Next version in 2 months
