### ISSUE TITLE
Add non-arbitrary inclusion rule

### ISSUE THREAD

**Issue by ghost** [FabioLolix/LinuxTimeline#43]
I'm planning to add distributions (if any missing) from [here](https://wiki.archlinux.org/index.php/Arch-based_distributions).

There should be non-arbitrary rule in place of what distribution does qualify for inclusion and what does not and should be removed.

For example distribution only qualifies if:

* 2 years since start to end date [you suggested](https://github.com/FabioLolix/LinuxTimeline/issues/31#issuecomment-320944899)
* forks require 2 years since parent distro start to own end date, in this case parent also qualifies

**Comment by razotivs** [comment]
Alternatively all can be included in spreadsheet but filtered out for final svg by those example rules.

**Comment by FabioLolix** [comment]
Hello @razotivs 

> 2 years since start to end date
> [...] what does not and should be removed.

I had blacklisted all or almost all distribution with a lifespan lower then that in the last year

> forks require 2 years

Can't wait 2 years to add a distribution but will not add it at day one either, can always be removed later

> There should be non-arbitrary rule in place of what distribution does qualify for inclusion

There aren't strict rules but I guess I will be more picky for future addition and give them a try, a test installation, I had bought a new laptop for this.

I had added distributions which have less then a year (Archlabs if rembember well) and will make it again, I guess for Artix and Archmerge, because they run stable software, which I can't say for Backslash

Rules for now:
* Use Linux kernel: so no Arch-Hurd or PacBSD
* at least 3 release (I know, an Arch derivate can make it in 3 months)
* Beta or stable release, this esclude projects with no release (like PostmarketOS) or in Alpha (like LiriOS, which is unusable)
* No remixes or remasters of iso just because

> I'm planning to add distributions (if any missing) from here.

There are several distribution missing from that list, you're welcome, one my goal is to add more Arch derivates

I have been contacted or I have on my todo list Hyperbola, BBQ, Bluestar and some more

**Comment by FabioLolix** [comment]
```

    forks require 2 years

Can't wait 2 years to add a distribution but will not add it at day one either, can always be removed later
```
I'm not in hurry to add distros anymore, will be added ones that have at least 2,5 years

**Comment by RefriZaddo** [comment]
> (Archlabs if rembember well)

umm @FabioLolix archlabs has about 6 years
