### ISSUE TITLE
OpenEmbedded based operating systems

### ISSUE THREAD

**Issue by kraj** [FabioLolix/LinuxTimeline#86]
I was looking through https://upload.wikimedia.org/wikipedia/commons/1/1b/Linux_Distribution_Timeline.svg

and i see few Operating systems which are made using openembedded, e.g. angstrom, webos, AsteroidOS, yocto project etc. I think like the roots ( debian Redhat arch android ) this could become a good root for embedded linux distributions.

**Comment by FabioLolix** [comment]
Hello @kraj and thank you for your patience

Before adding AsteroidOS I had an email exchange with its developer and we both agreed to not make an openembedded root because of lacks of binary & packaging compatibility between projects builded with  openembedded.

However in the distro archive I'm making I'm writing if a project use openembedded and we can make a dedicated list of projects using it.
Soon the timeline will link to the archive instead of the project website

* https://github.com/FabioLolix/fabiololix.gitlab.io
* https://gitlab.com/FabioLolix/fabiololix.gitlab.io
* https://fabiololix.gitlab.io/os/linux/a/asteroidos/ (still half done)

> yocto project 
I don't think it was ever in the timeline

By the way, how is going angstrom? can't reach the website

**Comment by kraj** [comment]
@FabioLolix thanks. Yes showing then rooted on OpenEmbedded would be a good start, since its not a binary distribution base there is a bit of difference, its a source based distro generation infrastructure. angstrom is still maintained. see 

https://github.com/angstrom-distribution

**Comment by FabioLolix** [comment]
> we can make a dedicated list of projects using it.

The list can be fullfilled here https://github.com/FabioLolix/fabiololix.gitlab.io/blob/master/docs/lists/builded-with-Buildroot-and-OpenEmbedded.md
